network:
  ethernets:
    eth0:
      match:
        macaddress: 50:3e:aa:10:23:93
      set-name: eth0
      dhcp4: false
      dhcp6: false
    eth1:
      match:
        macaddress: c8:7f:54:08:0c:fb
      set-name: eth1
      dhcp4: false
      dhcp6: false
      optional: true
  bridges:
    br0:
      addresses:
      - 192.168.0.11/24
      nameservers:
        addresses:
        - 192.168.1.15
        - 1.1.1.1
      routes:
      - to: default
        via: 192.168.0.1
      interfaces:
      - eth0
  version: 2
