network:
  ethernets:
    enp4s0:
      addresses:
      - 192.168.0.11/24
      nameservers:
        addresses:
        - 192.168.1.15
        - 1.1.1.1
    enp7s0:
      dhcp4: false
      dhcp6: false
      optional: true
  version: 2
