network:
  ethernets:
    enp5s0:
      addresses:
      - 192.168.0.12/24
      nameservers:
        addresses:
        - 192.168.1.15
        - 1.1.1.1
    enp9s0:
      dhcp4: false
      dhcp6: false
      optional: true
  version: 2
