network:
  ethernets:
    eth0:
      match:
        macaddress: 50:3e:aa:0e:54:6f
      set-name: eth0
      dhcp4: false
      dhcp6: false
    eth1:
      match:
        macaddress: 58:11:22:d8:9c:2f
      set-name: eth1
      dhcp4: false
      dhcp6: false
      optional: true
    vethb1: {}
    vethb2: {}
  bridges:
    br0:
      addresses:
      - 192.168.0.12/24
      nameservers:
        addresses:
        - 192.168.1.15
        - 1.1.1.1
      routes:
      - to: default
        via: 192.168.0.1
      interfaces:
      - eth0
      - vethb1
  version: 2
